export const resDaftarPesananBuyer = {
  Message: { Code: 200, Text: "Success" },
  Data: [
    {
      orderID: "550e8400-e29b-41d4-a716-446655440000",
      transaction: [
        {
          transactionID: "TXN123456",
          invoiceId: "INV/20240124/MPM/000001",
          invoiceLink: "http://example.com/invoice/INV/20240124/MPM/000001",
          sellerID: "SELLER123",
          storeName: "Priority Tire",
          statusBuyer: "Menunggu Pembayaran",
          statusInfo: {
            text: "Lakukan pembayaran sebelum",
            date: "20 Sep 2024 13:00 WIB",
            bg: "warning-100",
            textColor: "warning-900",
          },
          products: [
            {
              id: "PROD123",
              productName: "Kampas Kopling Quester (Disc Clutch) N3100-NA04AD",
              photo: "https://prd.place/170?id=1.png",
              priceBeforeDiscount: 150000,
              priceAfterDiscount: 120000,
              discount: "",
              qty: 20,
              notes: "Handle with care",
              salesType: "Retail",
              haveVariant: false,
              minPurchase: 1,
              variant: {
                id: "8273",
                variantName: "Crown Wheel, Fuso 7x4",
              },
              subtotal: 12035000,
            },
            {
              id: "PROD124",
              productName: "Kampas Kopling Quester (Disc Clutch) N3100-NA04AD",
              photo: "https://prd.place/170?id=2.png",
              priceBeforeDiscount: 100000,
              priceAfterDiscount: 80000,
              discount: "20% OFF",
              qty: 20,
              notes: "Handle with care",
              salesType: "Retail",
              haveVariant: false,
              minPurchase: 1,
              variant: {
                id: "",
                variantName: "Paling keren",
              },
              subtotal: 7800000,
            },
            {
              id: "PROD125",
              productName: "Kampas Kopling Quester (Disc Clutch) N3100-NA04AD",
              photo: "https://prd.place/170?id=3.png",
              priceBeforeDiscount: 150000,
              priceAfterDiscount: 120000,
              discount: "20% OFF",
              qty: 20,
              notes: "Handle with care",
              salesType: "Retail",
              haveVariant: false,
              minPurchase: 1,
              variant: {
                id: "",
                variantName: "",
              },
              subtotal: 12035000,
            },
          ],
        },
        {
          transactionID: "TXN123457",
          invoiceId: "INV/20240124/MPM/000002",
          invoiceLink: "http://example.com/invoice/INV/20240124/MPM/000002",
          sellerID: "SELLER123",
          storeName: "Priority Tire",
          statusBuyer: "Menunggu Pembayaran",
          statusInfo: {
            text: "Dibatalkan otomatis pada",
            date: "20 Sep 2024 13:00 WIB",
            bg: "warning-100",
            textColor: "warning-900",
          },
          products: [
            {
              id: "PROD124",
              productName: "Kampas Kopling Quester (Disc Clutch) N3100-NA04AD",
              photo: "https://prd.place/170?id=3.png",
              priceBeforeDiscount: 100000,
              priceAfterDiscount: 7800000 / 20,
              discount: "20% OFF",
              qty: 20,
              notes: "Handle with care",
              salesType: "Retail",
              haveVariant: false,
              minPurchase: 1,
              variant: {
                id: "",
                variantName: "",
              },
              subtotal: 7800000,
            },
          ],
        },
      ],
      orderDate: "28 Sep 2024 13:00 WIB",
      grandTotal: 19870000,
    },
    {
      orderID: "550e8400-e29b-41d4-a716-446655440001",
      transaction: [
        {
          transactionID: "TXN123457",
          invoiceId: "INV/20240124/MPM/000002",
          invoiceLink: "http://example.com/invoice/INV/20240124/MPM/000002",
          sellerID: "SELLER123",
          storeName: "Priority Tire",
          statusBuyer: "Menunggu Pembayaran",
          statusInfo: {
            text: "Dibatalkan otomatis pada",
            date: "20 Sep 2024 13:00 WIB",
            bg: "warning-100",
            textColor: "warning-900",
          },
          products: [
            {
              id: "PROD124",
              productName: "Kampas Kopling Quester (Disc Clutch) N3100-NA04AD",
              photo: "https://prd.place/170?id=3.png",
              priceBeforeDiscount: 100000,
              priceAfterDiscount: 7800000 / 20,
              discount: "20% OFF",
              qty: 20,
              notes: "Handle with care",
              salesType: "Retail",
              haveVariant: false,
              minPurchase: 1,
              variant: {
                id: "",
                variantName: "",
              },
              subtotal: 7800000,
            },
          ],
        },
      ],
      orderDate: "28 Sep 2024 13:00 WIB",
      grandTotal: 7800000,
    },
  ],
};
