import { create } from "zustand";
export const defaultFilterProduct = {
    q:"",
    groupcategoryID: [],
    categoryID: [],
    subcategoryID: [],
    itemID: [],
    startPrice: 0,
    endPrice: 0,
    cityID: [],
    brandProductID: [],
    salesType: [],
    conditionID: [],
    vehicleID: "",
    brandID: "",
    year: "",
    modelID: "",
    typeID:"",
    garageID: "",
    radius: 0,
    latitude: 0,
    longitude: 0,
    shippingType: [],
    lastOnline: [],
    promo: [],
    rating: [],
    alias:false,
    type:"",
    limit:10,
    page:1,
    distance:[],
    order:"",
    mode:"",
}
export const filterProduct = create((set,get)=>({
    q:"",
    groupcategoryID: [],
    categoryID: [],
    subcategoryID: [],
    itemID: [],
    startPrice: 0,
    endPrice: 0,
    cityID: [],
    brandProductID: [],
    salesType: [],
    conditionID: [],
    vehicleID: "",
    brandID: "",
    year: "",
    modelID: "",
    typeID:"",
    garageID: "",
    radius: 0,
    latitude: 0,
    longitude: 0,
    shippingType: [],
    lastOnline: [],
    promo: [],
    rating: [],
    alias:false,
    type:"",
    limit:10,
    page:1,
    distance:[],
    order:"",
    mode:"",
    setFilterProduct: (field,val)=>{
        let value = field==='alias'?!!(val):val
        set({[field]:value})
    },
    setFilter:(val)=>set({...get(),...val}),
    setAllFilter:(val)=>set(val),
    resetFilter:()=>set({
        // 24. THP 2 - MOD001 - MP - 016 - QC Plan - Web - MuatParts - Paket 024 B - Homepage Buyer - LB - 0191
        groupcategoryID: [],
        categoryID: [],
        subcategoryID: [],
        itemID: [],
        startPrice: 0,
        endPrice: 0,
        cityID: [],
        brandProductID: [],
        salesType: [],
        conditionID: [],
        vehicleID: "",
        brandID: "",
        year: "",
        modelID: "",
        typeID:"",
        garageID: "",
        radius: 0,
        latitude: "",
        longitude: "",
        shippingType: [],
        lastOnline: [],
        promo: [],
        rating: [],
        alias:false,
        type:"",
        limit:10,
        page:1,
        distance:[],
        order:"",
        mode:"",
      })
}))