export const resIdPesanan = {
  Message: {
    Code: 200,
    Text: "OK",
  },
  Data: {
    orderID: "22e54f6e-0563-4a3b-920c-6e66d1fa75fd",
    statusInfoSeller: {
      status: "Siap Dikirim",
      title_text: "Pembayaran Berhasil",
      subtitle_text:
        "Pembayaran telah berhasil pada <b>26 Jan 2024 11.51 WIB</b>",
      icon: "check",
      bg: "success-50",
      textColor: "success-400",
    },
    // statusInfoBuyer: {
    //   status: "Menunggu Pembayaran",
    //   title_text: "Menunggu Direspon",
    //   subtitle_text:
    //     "Menunggu respon penjual paling lama pada  26 Jan 2024 11:51 WIB. Apabila dalam waktu tersebut penjual tidak merespon, maka pesananmu akan otomatis dibatalkan dan dana akan dikembalikan ke kamu",
    //   icon: "check",
    //   bg: "success-50",
    //   textColor: "success-400",
    // },
    statusInfoBuyer: {
      status: "Menunggu Direspon",
      title_text: "Menunggu Direspon",
      subtitle_text:
        "Menunggu respon penjual paling lama pada  26 Jan 2024 11:51 WIB. Apabila dalam waktu tersebut penjual tidak merespon, maka pesananmu akan otomatis dibatalkan dan dana akan dikembalikan ke kamu",
      icon: "check",
      bg: "success-50",
      textColor: "success-400",
    },
    // statusInfoBuyer: {
    //   status: "Dikemas",
    //   title_text: "Pengemasan Produk",
    //   subtitle_text:
    //     "Penjual sedang menyiapkan pesananmu. Akan dikirim paling lambat pada 26 Jan 2024 11:51 WIB",
    //   icon: "check",
    //   bg: "success-50",
    //   textColor: "success-400",
    // },
    // statusInfoBuyer: {
    //   status: "Dikirim",
    //   title_text: "Dikirim",
    //   subtitle_text:
    //     "Pesananmu dalam proses pengiriman oleh kurir",
    //   icon: "check",
    //   bg: "success-50",
    //   textColor: "success-400",
    // },
    // statusInfoBuyer: {
    //   status: "Tiba di Tujuan",
    //   title_text: "Tiba di Tujuan",
    //   subtitle_text:
    //     "Pesananmu telah tiba di tujuan",
    //   icon: "check",
    //   bg: "success-50",
    //   textColor: "success-400",
    // },
    // statusInfoBuyer: {
    //   status: "Dibatalkan Penjual",
    //   title_text: "Dibatalkan Penjual",
    //   subtitle_text:
    //     "Pesanan telah dibatalkan oleh penjual karena {alasan_pembatalan}",
    //   icon: "check",
    //   bg: "success-50",
    //   textColor: "success-400",
    // },
    storeOrders: [
      {
        transactionID: "22e54f6e-0563-4a3b-920c-6e66d1fa75fd",
        invoiceNumber: "INV/2025/01/06/MPM/24910",
        storeName: "TokoHasyim 5",
        shippingOrigin: "Kota Tangerang",
        items: [
          {
            productName: "Kabel Jumper Tronton",
            productDetails: "Variant paling keren",
            quantity: 2,
            originalPrice: 150000,
            originalPromoPrice: 120000,
            discountedPercentage: 20,
            note: "Catatan: Mohon Double Packing",
            imageUrl: "https://prd.place/170?id=2.png",
          },
          {
            productName: "Kabel Jumper Tronton",
            productDetails: "Variant paling keren",
            quantity: 1,
            originalPrice: 150000,
            originalPromoPrice: 120000,
            discountedPercentage: 20,
            note: "Catatan: Mohon Double Packing",
            imageUrl: "https://prd.place/170?id=2.png",
          },
        ],
        shippingInfo: {
          courier: "Hasyim",
          trackingNumber: "346856",
          recipientAddressName: "Gudang Indonesia Keren",
          recipientAddress:
            "Jl. Pelawarna no 20, Kota Kediri, Jawa Timur, 61665",
          recipientName: "Joko",
          recipientPhone: "081123123123",
          note: "Catatan: Mohon Double Packing",
          trackingHistory: [
            {
              status: "Pembayaran Berhasil",
              timestamp: "2025-01-06T05:02:38.943Z",
              description: "(Menunggu Pesanan dikonfirmasi ke Penjual)",
              proofUrl: null,
            },
            {
              status: "Pesanan Dibuat",
              timestamp: "2025-01-06T05:02:38.943Z",
              description: "(Pembeli membuat pesanan)",
              proofUrl: null,
            },
          ],
        },
        statusSeller: "Pesanan Masuk",
        statusBuyer: "Menunggu Pembayaran",
        subTotal: 434000,
        totalPrice: 360000,
        shippingCost: 60000,
        insuranceCost: 14000,
        weight: 1000,
        responseDeadline: "2025-01-08T05:02:38.748Z",
      },
      // {
      //   transactionID: "22e54f6e-0563-4a3b-920c-6e66d1fa75fd",
      //   invoiceNumber: "INV/2025/01/06/MPM/24910",
      //   storeName: "TokoHasyim 5",
      //   shippingOrigin: "Kota Tangerang",
      //   items: [
      //     {
      //       productName: "Kabel Jumper Tronton",
      //       productDetails: "Variant paling keren",
      //       quantity: 2,
      //       originalPrice: 150000,
      //       originalPromoPrice: 120000,
      //       discountedPercentage: 20,
      //       note: "Catatan: Mohon Double Packing",
      //       imageUrl: "https://prd.place/170?id=2.png",
      //     },
      //     {
      //       productName: "Kabel Jumper Tronton",
      //       productDetails: "Variant paling keren",
      //       quantity: 1,
      //       originalPrice: 150000,
      //       originalPromoPrice: 120000,
      //       discountedPercentage: 20,
      //       note: "Catatan: Mohon Double Packing",
      //       imageUrl: "https://prd.place/170?id=2.png",
      //     },
      //   ],
      //   shippingInfo: {
      //     courier: "Hasyim",
      //     trackingNumber: "346856",
      //     recipientAddressName: "Gudang Indonesia Keren",
      //     recipientAddress:
      //       "Jl. Pelawarna no 20, Kota Kediri, Jawa Timur, 61665",
      //     recipientName: "Joko",
      //     recipientPhone: "081123123123",
      //     note: "Catatan: Mohon Double Packing",
      //     trackingHistory: [
      //       {
      //         status: "Pesanan Dibuat",
      //         timestamp: "2025-01-06T05:02:38.943Z",
      //         description: "Pesanan Dibuat",
      //         proofUrl: null,
      //       },
      //     ],
      //   },
      //   statusSeller: "Pesanan Masuk",
      //   statusBuyer: "Menunggu Pembayaran",
      //   subTotal: 434000,
      //   totalPrice: 360000,
      //   shippingCost: 60000,
      //   insuranceCost: 14000,
      //   weight: 1000,
      //   responseDeadline: "2025-01-08T05:02:38.748Z",
      // },
    ],
    cancellationReason: "",
    completedAt: null,
    paymentInfo: {
      paymentDeadline: "2025-01-10T05:02:38.985Z",
      paymentMethod: "BCA Virtual Account",
      virtualAccount: "56897730751175834156223",
      methodLogo: "",
      totalBill: 871000,
      platformFee: 3000,
      totalOrder: 868000,
    },
  },
  Type: "/v1/muatparts/buyer/orders/detail?orderID=22e54f6e-0563-4a3b-920c-6e66d1fa75fd&page=menunggu_pembayaran",
};
